#!/usr/bin/env python3
"""Headless veri profili.

Çıktılar:
  artifacts/data_profile.json
  reports/initial_data_profile.md
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from src.data.loader import load_raw  # noqa: E402
from src.data.schemas import check_schema, ENTITY_COLUMNS  # noqa: E402


def basic_stats(df: pd.DataFrame) -> dict:
    fraud_n = int(df["IsFraudTransaction"].sum())
    return {
        "n_rows": len(df),
        "n_cols": df.shape[1],
        "memory_mb": round(df.memory_usage(deep=True).sum() / 1024 / 1024, 2),
        "fraud_count": fraud_n,
        "fraud_rate": round(df["IsFraudTransaction"].mean(), 6),
        "imbalance_ratio_1_to": int(round(1 / df["IsFraudTransaction"].mean())) if fraud_n else None,
        "date_min": str(df["TransactionDate"].min()),
        "date_max": str(df["TransactionDate"].max()),
        "date_span_days": int((df["TransactionDate"].max() - df["TransactionDate"].min()).days),
        "duplicates_full_row": int(df.duplicated().sum()),
        "duplicates_business_key": int(df["BusinessKey"].duplicated().sum()),
    }


def missing(df: pd.DataFrame) -> dict:
    m = df.isna().sum()
    m = m[m > 0]
    return {c: {"n": int(v), "pct": round(float(v / len(df) * 100), 4)} for c, v in m.items()}


def cardinality(df: pd.DataFrame) -> dict:
    return {c: int(df[c].nunique(dropna=True)) for c in df.columns}


def breakdown(df: pd.DataFrame, col: str) -> list[dict]:
    g = df.groupby(col, dropna=False).agg(n=("IsFraudTransaction", "size"),
                                          fraud=("IsFraudTransaction", "sum"))
    g["rate_pct"] = (g["fraud"] / g["n"] * 100).round(4)
    g = g.sort_values("n", ascending=False)
    return [
        {"value": str(idx), "n": int(row.n), "fraud": int(row.fraud), "rate_pct": float(row.rate_pct)}
        for idx, row in g.iterrows()
    ]


def quarterly(df: pd.DataFrame) -> list[dict]:
    q = df.groupby(df["TransactionDate"].dt.to_period("Q")).agg(
        n=("IsFraudTransaction", "size"), fraud=("IsFraudTransaction", "sum"))
    q["rate_pct"] = (q["fraud"] / q["n"] * 100).round(4)
    return [{"quarter": str(idx), "n": int(r.n), "fraud": int(r.fraud), "rate_pct": float(r.rate_pct)}
            for idx, r in q.iterrows()]


def entity_summary(df: pd.DataFrame, col: str) -> dict:
    g = df.groupby(col).agg(n=("IsFraudTransaction", "size"),
                            fraud=("IsFraudTransaction", "sum"))
    desc = g["n"].describe(percentiles=[0.5, 0.9, 0.99]).to_dict()
    return {
        "unique_entities": int(g.shape[0]),
        "tx_per_entity_mean": round(float(desc["mean"]), 3),
        "tx_per_entity_median": float(desc["50%"]),
        "tx_per_entity_p90": float(desc["90%"]),
        "tx_per_entity_p99": float(desc["99%"]),
        "tx_per_entity_max": int(g["n"].max()),
        "entities_with_fraud": int((g["fraud"] > 0).sum()),
        "entities_with_only_fraud": int(((g["fraud"] == g["n"]) & (g["n"] >= 1)).sum()),
    }


def main() -> None:
    out_json = REPO / "artifacts" / "data_profile.json"
    out_md = REPO / "reports" / "initial_data_profile.md"

    df = load_raw()
    schema = check_schema(df)
    profile = {
        "schema": {
            "ok": schema.ok,
            "missing": list(schema.missing),
            "extra": list(schema.extra),
        },
        "basic": basic_stats(df),
        "missing": missing(df),
        "cardinality": cardinality(df),
        "quarterly_fraud": quarterly(df),
        "breakdowns": {
            col: breakdown(df, col)
            for col in [
                "TransactionType", "TransactionChannel", "DeviceOSName",
                "HasMobileActivationL1H", "HasMobileActivationL8H",
                "DayType", "CustomerSegment", "CustomerGender",
                "IsFractionalAmount",
            ]
        },
        "entities": {col: entity_summary(df, col) for col in ENTITY_COLUMNS},
    }

    out_json.parent.mkdir(parents=True, exist_ok=True)
    with open(out_json, "w") as f:
        json.dump(profile, f, indent=2, default=str, ensure_ascii=False)

    md = _render_md(profile)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(md, encoding="utf-8")

    print(f"OK — wrote {out_json}")
    print(f"OK — wrote {out_md}")


def _render_md(p: dict) -> str:
    b = p["basic"]
    lines: list[str] = []
    lines.append("# Initial Data Profile\n")
    lines.append(f"> Auto-generated by `scripts/00_inspect_data.py`.\n")
    lines.append("## Schema\n")
    lines.append(f"- OK: **{p['schema']['ok']}**")
    lines.append(f"- Missing columns: {p['schema']['missing'] or 'yok'}")
    lines.append(f"- Extra columns: {p['schema']['extra'] or 'yok'}\n")
    lines.append("## Boyut & temel istatistik\n")
    lines.append(f"- Satır × sütun: **{b['n_rows']:,} × {b['n_cols']}**")
    lines.append(f"- Bellek (pandas, deep): {b['memory_mb']} MB")
    lines.append(f"- Tarih aralığı: **{b['date_min']}** → **{b['date_max']}** ({b['date_span_days']} gün)")
    lines.append(f"- Fraud sayısı / oran: **{b['fraud_count']:,}** / **{b['fraud_rate']*100:.4f}%** (1:{b['imbalance_ratio_1_to']})")
    lines.append(f"- Duplicate (full-row / BusinessKey): {b['duplicates_full_row']} / {b['duplicates_business_key']}\n")

    lines.append("## Eksik değerler\n")
    if not p["missing"]:
        lines.append("- (eksik yok)\n")
    else:
        lines.append("| Kolon | n | % |")
        lines.append("|---|---:|---:|")
        for c, m in p["missing"].items():
            lines.append(f"| {c} | {m['n']:,} | {m['pct']}% |")
        lines.append("")

    lines.append("## Cardinality\n")
    lines.append("| Kolon | unique |")
    lines.append("|---|---:|")
    for c, n in p["cardinality"].items():
        lines.append(f"| {c} | {n:,} |")
    lines.append("")

    lines.append("## Çeyreklik fraud oranı\n")
    lines.append("| Çeyrek | n | fraud | oran (%) |")
    lines.append("|---|---:|---:|---:|")
    for r in p["quarterly_fraud"]:
        lines.append(f"| {r['quarter']} | {r['n']:,} | {r['fraud']:,} | {r['rate_pct']} |")
    lines.append("")

    lines.append("## Kırılım fraud oranları\n")
    for col, rows in p["breakdowns"].items():
        lines.append(f"### {col}\n")
        lines.append("| Değer | n | fraud | oran (%) |")
        lines.append("|---|---:|---:|---:|")
        for r in rows:
            lines.append(f"| {r['value']} | {r['n']:,} | {r['fraud']:,} | {r['rate_pct']} |")
        lines.append("")

    lines.append("## Entity özetleri\n")
    lines.append("| Entity | unique | tx/entity (med / p99 / max) | fraud-yapan | yalnız-fraud |")
    lines.append("|---|---:|---|---:|---:|")
    for col, s in p["entities"].items():
        lines.append(
            f"| {col} | {s['unique_entities']:,} | {s['tx_per_entity_median']:.0f} / "
            f"{s['tx_per_entity_p99']:.0f} / {s['tx_per_entity_max']:,} | "
            f"{s['entities_with_fraud']:,} | {s['entities_with_only_fraud']:,} |"
        )
    lines.append("")

    lines.append("## Yorum (kısa)\n")
    lines.append(
        "- Fraud oranı %0.63 → ciddi imbalance. Accuracy yanıltıcıdır.\n"
        "- Çeyreklik fraud oranı 30x oynuyor — neden veriden tek başına çıkarılamaz "
        "(temporal drift / label policy / synthetic artifact ihtimalleri açık).\n"
        "- `TransactionChannel` tek değerli → drop.\n"
        "- `DayType` %96 NaN — anlamı belirsiz; NaN→'Normal' vs NaN→'Unknown' iki varyantı test edilecek.\n"
        "- AccountNumber neredeyse her satırda unique → hesap-bazlı historical FE üretilemez.\n"
        "- DeviceId paylaşılıyor (medyan 21 tx/cihaz) → cihaz-bazlı historical FE güçlü potansiyel.\n"
    )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    main()
