#!/usr/bin/env python3
"""Adversarial validation — train vs test arasında dağılım farkını ölçer.

Algoritma (Kaggle pattern):
  1. Train satırlarına is_test=0, test satırlarına is_test=1 etiketi ver.
  2. Tüm feature'larla bir classifier eğit (binary: train vs test).
  3. ROC-AUC oku:
     - AUC ≈ 0.5 → dağılımlar aynı (sağlıklı).
     - AUC >> 0.5 → drift var; classifier kolayca ayırıyor.
  4. Classifier feature importance → drift'i hangi feature'lar yaratıyor.

Output: artifacts/adversarial_validation.json + reports/adversarial_validation.md

NOT: Bu performans iyileştirme değil. Drift teşhisi. Production'da hangi feature'ların
zaman içinde dağılım değiştirdiğini bilmek için kritik.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from sklearn.ensemble import HistGradientBoostingClassifier  # noqa: E402
from sklearn.compose import ColumnTransformer  # noqa: E402
from sklearn.impute import SimpleImputer  # noqa: E402
from sklearn.preprocessing import OrdinalEncoder  # noqa: E402
from sklearn.pipeline import Pipeline  # noqa: E402
from sklearn.metrics import roc_auc_score  # noqa: E402

from src.data.loader import load_validated  # noqa: E402
from src.features.instant import add_derived  # noqa: E402
from src.features.historical import add_label_free_aggregates, add_label_dependent_aggregates  # noqa: E402
from src.models.split import time_based_split  # noqa: E402
from src.models.train import _feature_columns  # noqa: E402


def build_frame() -> pd.DataFrame:
    df, _ = load_validated()
    df = add_derived(df, daytype_nan="unknown")
    df = add_label_free_aggregates(df)
    df = add_label_dependent_aggregates(df, label_lag_days=7, prior_strength=50)
    return df


def main():
    print("[adv] Loading + FE …")
    df = build_frame()
    split = time_based_split(df)
    print(f"[adv] Train {len(split.train):,} | Test {len(split.test):,}")

    num, cat = _feature_columns(df, drop_demographic=True)
    feat = num + cat
    # IsFraudTransaction'ı kesinlikle çıkar (zaten DROP_FOR_FEATURES'da ama emin olalım)
    feat = [c for c in feat if c != "IsFraudTransaction"]

    # is_test target
    train = split.train.copy().assign(is_test=0)
    test = split.test.copy().assign(is_test=1)
    combined = pd.concat([train, test], ignore_index=True)
    shuffled = combined.sample(frac=1.0, random_state=42).reset_index(drop=True)

    # 80/20 internal split for adversarial classifier
    n = len(shuffled)
    cut = int(n * 0.8)
    Xa_tr, ya_tr = shuffled.iloc[:cut][feat], shuffled.iloc[:cut]["is_test"].to_numpy()
    Xa_va, ya_va = shuffled.iloc[cut:][feat], shuffled.iloc[cut:]["is_test"].to_numpy()

    pre = ColumnTransformer([
        ("num", SimpleImputer(strategy="median"), num),
        ("cat", Pipeline([
            ("imp", SimpleImputer(strategy="most_frequent")),
            ("ord", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)),
        ]), cat),
    ])
    cat_idx = list(range(len(num), len(num) + len(cat)))
    clf = HistGradientBoostingClassifier(
        learning_rate=0.05, max_iter=200, max_leaf_nodes=31,
        min_samples_leaf=200, categorical_features=cat_idx, random_state=42,
    )
    pipe = Pipeline([("pre", pre), ("clf", clf)])
    print("[adv] Training adversarial classifier (train vs test) …")
    pipe.fit(Xa_tr, ya_tr)
    proba = pipe.predict_proba(Xa_va)[:, 1]
    adv_auc = roc_auc_score(ya_va, proba)
    print(f"[adv] Adversarial ROC-AUC = {adv_auc:.4f}")
    print("       (0.5 = no drift, ≥0.7 = significant drift, ≥0.9 = severe)")

    # Per-feature drift via permutation importance
    print("[adv] Computing permutation importance per feature …")
    from sklearn.inspection import permutation_importance
    sample_idx = np.random.RandomState(0).choice(len(Xa_va), min(20000, len(Xa_va)), replace=False)
    pi = permutation_importance(
        pipe, Xa_va.iloc[sample_idx], ya_va[sample_idx],
        n_repeats=3, random_state=0, scoring="roc_auc", n_jobs=-1,
    )
    imp = pd.Series(pi.importances_mean, index=feat).sort_values(ascending=False)

    top_drift = imp.head(20).to_dict()
    payload = {
        "adversarial_roc_auc": float(adv_auc),
        "interpretation": (
            "0.5 ≈ no drift; 0.6-0.7 mild; 0.7-0.85 significant; ≥0.85 severe."
            f" Current: {adv_auc:.3f}."
        ),
        "n_features": len(feat),
        "top_20_drift_features": {k: float(v) for k, v in top_drift.items()},
    }
    out = REPO / "artifacts" / "adversarial_validation.json"
    out.write_text(json.dumps(payload, indent=2))
    print(f"[adv] wrote {out}")

    # Markdown report
    md = ["# Adversarial Validation — train ↔ test drift teşhisi\n"]
    md.append(f"> Auto-generated by `scripts/adversarial_validation.py`. JSON: `artifacts/adversarial_validation.json`.\n")
    md.append("## Sonuç\n")
    md.append(f"**Adversarial ROC-AUC = {adv_auc:.4f}**\n")
    md.append("| Aralık | Yorum |")
    md.append("|---|---|")
    md.append("| ≈ 0.50 | Drift yok — train ve test aynı dağılım |")
    md.append("| 0.55-0.65 | Hafif drift |")
    md.append("| 0.65-0.80 | Belirgin drift — modeli etkileyebilir |")
    md.append("| 0.80-0.95 | Şiddetli drift — split veya feature engineering revize edilmeli |")
    md.append("| ≥ 0.95 | Critical — temporal leakage olabilir |\n")
    md.append("## Drift'e en çok katkı yapan 20 feature\n")
    md.append("| Feature | Permutation drift importance |")
    md.append("|---|---:|")
    for k, v in top_drift.items():
        md.append(f"| `{k}` | {v:.4f} |")
    md.append("")
    md.append("### Yorum\n")
    if adv_auc < 0.6:
        md.append("Drift seviyesi düşük — train/test dağılımları büyük ölçüde benzer. Mevcut model sağlıklı.")
    elif adv_auc < 0.8:
        md.append("Belirgin drift var. Yukarıdaki listedeki feature'lar zaman içinde dağılım değiştiriyor. Production'da bu feature'ların PSI'ı periyodik izlenmeli; gerekirse re-training tetiklenmeli.")
    else:
        md.append("Şiddetli drift! Bu seviyede performans rakamları yanıltıcı olabilir. Feature engineering ve/veya split stratejisi revize edilmeli.")
    out_md = REPO / "reports" / "adversarial_validation.md"
    out_md.write_text("\n".join(md), encoding="utf-8")
    print(f"[adv] wrote {out_md}")


if __name__ == "__main__":
    main()
